apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-170279018
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/3yttqs7g-tenant/test-app-170279018/go-170279018@sha256:8f7dc02d1f5e65250c1f56602bc1c27204d5007c8d62bd9ce540aaa47a291eeb
        name: my-go
        resources: {}
status: {}
