apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170279018
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170279018
    app.kubernetes.io/part-of: test-app-170279018
  name: go-170279018
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-170279018
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-170279018
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/3yttqs7g-tenant/test-app-170279018/go-170279018@sha256:8f7dc02d1f5e65250c1f56602bc1c27204d5007c8d62bd9ce540aaa47a291eeb
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
